#!/usr/bin/env python3
"""Fail when Localizable.xcstrings gains junk auto-extracted keys.

Xcode's SWIFT_EMIT_LOC_STRINGS extractor treats bare Text("—") and
LocalizedStringKey interpolations like Text("\\(count)") as catalog keys.
Provenencia keys must be semantic dotted names (onboarding.welcomeTitle).
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "macos" / "App" / "Resources" / "Localizable.xcstrings"

# Product keys: start with a letter, then letters / digits / . / _
KEY_RE = re.compile(r"^[a-z][a-zA-Z0-9._]*$")


def main() -> int:
    if not CATALOG.is_file():
        print(f"error: missing {CATALOG}", file=sys.stderr)
        return 2

    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    strings = data.get("strings")
    if not isinstance(strings, dict):
        print("error: Localizable.xcstrings missing strings object", file=sys.stderr)
        return 2

    problems: list[str] = []
    for key, entry in strings.items():
        if not isinstance(entry, dict):
            problems.append(f"{key!r}: entry must be an object")
            continue
        if not KEY_RE.match(key):
            problems.append(
                f"{key!r}: key must be a semantic dotted name "
                f"(e.g. workspace.omnibar.searchFailed). "
                f"Use Text(verbatim:) / Text(verbatim: \"\\(x)\") for glyphs and "
                f"interpolated accessibility values so Xcode does not extract them."
            )
        state = entry.get("extractionState")
        if state == "extracted_with_value":
            problems.append(
                f"{key!r}: extractionState is extracted_with_value — "
                f"wire through L10n and set extractionState to manual"
            )
        if entry.get("isCommentAutoGenerated") is True:
            problems.append(
                f"{key!r}: isCommentAutoGenerated — remove this auto-extracted "
                f"entry and fix the call site (Text(verbatim:) or L10n)"
            )

    if problems:
        print(
            f"Localizable.xcstrings lint failed ({len(problems)} issue(s)):",
            file=sys.stderr,
        )
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    print(f"OK: {len(strings)} keys in {CATALOG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
