#!/usr/bin/env python3
"""Fail when Localizable.xcstrings gains junk keys or misses L10n keys.

Xcode's SWIFT_EMIT_LOC_STRINGS extractor treats bare Text("—") and
LocalizedStringKey interpolations like Text("\\(count)") as catalog keys.
Provenencia keys must be semantic dotted names (onboarding.welcomeTitle).

Every LocalizedStringResource key in the app must also be in the catalog.
L10n.string resolves through Bundle.localizedString, which ignores the
resource's defaultValue and shows the raw key when the catalog lacks it.

No LocalizedStringResource may interpolate (defaultValue: "\\(count) items").
Copy with arguments is a catalog format filled by an L10n format function
returning String, so every resource stays safe to resolve with L10n.string.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / "macos" / "App" / "Resources" / "Localizable.xcstrings"
APP_SOURCES = ROOT / "macos" / "App"

# Product keys: start with a letter, then letters / digits / . / _
KEY_RE = re.compile(r"^[a-z][a-zA-Z0-9._]*$")

# The first argument of LocalizedStringResource(...): its catalog key.
RESOURCE_KEY_RE = re.compile(r'LocalizedStringResource\(\s*"([^"\\]+)"')


# A LocalizedStringResource whose key or defaultValue literal interpolates.
INTERPOLATED_RESOURCE_RE = re.compile(
    r'LocalizedStringResource\(\s*"[^"\n]*(?:\\\(|"\s*,\s*defaultValue:\s*"[^"\n]*\\\()'
)


def interpolated_resources() -> list[tuple[Path, int]]:
    """(file, line) of every LocalizedStringResource that interpolates a value."""
    hits: list[tuple[Path, int]] = []
    for path in sorted(APP_SOURCES.rglob("*.swift")):
        text = path.read_text(encoding="utf-8")
        for match in INTERPOLATED_RESOURCE_RE.finditer(text):
            hits.append((path, text.count("\n", 0, match.start()) + 1))
    return hits


def resource_keys() -> dict[str, Path]:
    """Every dotted LocalizedStringResource key in the app, with one file that uses it.

    Non-dotted keys are SwiftUI preview placeholders (LocalizedStringResource("Save")),
    not catalog copy.
    """
    keys: dict[str, Path] = {}
    for path in sorted(APP_SOURCES.rglob("*.swift")):
        for key in RESOURCE_KEY_RE.findall(path.read_text(encoding="utf-8")):
            if KEY_RE.match(key) and "." in key:
                keys.setdefault(key, path)
    return keys


def main() -> int:
    if not CATALOG.is_file():
        print(f"error: missing {CATALOG}", file=sys.stderr)
        return 2

    data = json.loads(CATALOG.read_text(encoding="utf-8"))
    strings = data.get("strings")
    if not isinstance(strings, dict):
        print("error: Localizable.xcstrings missing strings object", file=sys.stderr)
        return 2

    problems: list[str] = []
    for key, entry in strings.items():
        if not isinstance(entry, dict):
            problems.append(f"{key!r}: entry must be an object")
            continue
        if not KEY_RE.match(key):
            problems.append(
                f"{key!r}: key must be a semantic dotted name "
                f"(e.g. workspace.omnibar.searchFailed). "
                f"Use Text(verbatim:) / Text(verbatim: \"\\(x)\") for glyphs and "
                f"interpolated accessibility values so Xcode does not extract them."
            )
        state = entry.get("extractionState")
        if state == "extracted_with_value":
            problems.append(
                f"{key!r}: extractionState is extracted_with_value — "
                f"wire through L10n and set extractionState to manual"
            )
        if entry.get("isCommentAutoGenerated") is True:
            problems.append(
                f"{key!r}: isCommentAutoGenerated — remove this auto-extracted "
                f"entry and fix the call site (Text(verbatim:) or L10n)"
            )

    for key, path in resource_keys().items():
        if key not in strings:
            problems.append(
                f"{key!r}: used in {path.relative_to(ROOT)} but missing from the "
                f"catalog — L10n.string would show the raw key"
            )

    for path, line in interpolated_resources():
        problems.append(
            f"{path.relative_to(ROOT)}:{line}: LocalizedStringResource interpolates a "
            f"value — give it a %@ / %lld catalog format and an L10n format "
            f"function returning String"
        )

    if problems:
        print(
            f"Localizable.xcstrings lint failed ({len(problems)} issue(s)):",
            file=sys.stderr,
        )
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    print(f"OK: {len(strings)} keys in {CATALOG.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
