// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: engine.proto

package engine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Method identifies the FFI operation. The C ABI is one call that takes this
// discriminant plus a protobuf payload; it is not a per-field getter surface.
type Method int32

const (
	Method_METHOD_UNSPECIFIED             Method = 0
	Method_METHOD_PING                    Method = 1
	Method_METHOD_GET_VERSION             Method = 2
	Method_METHOD_GET_INSTALL_IDENTITY    Method = 3
	Method_METHOD_COMPLETE_ONBOARDING     Method = 4
	Method_METHOD_REMOVE_INSTALL_IDENTITY Method = 5
	Method_METHOD_GET_ACTIVE_PROJECT      Method = 6
	Method_METHOD_OPEN_PROJECT            Method = 7
	Method_METHOD_REMOVE_ACTIVE_PROJECT   Method = 8
	Method_METHOD_LIST_PROJECT_USERS      Method = 9
	Method_METHOD_SIGN_OUT                Method = 10
)

// Enum value maps for Method.
var (
	Method_name = map[int32]string{
		0:  "METHOD_UNSPECIFIED",
		1:  "METHOD_PING",
		2:  "METHOD_GET_VERSION",
		3:  "METHOD_GET_INSTALL_IDENTITY",
		4:  "METHOD_COMPLETE_ONBOARDING",
		5:  "METHOD_REMOVE_INSTALL_IDENTITY",
		6:  "METHOD_GET_ACTIVE_PROJECT",
		7:  "METHOD_OPEN_PROJECT",
		8:  "METHOD_REMOVE_ACTIVE_PROJECT",
		9:  "METHOD_LIST_PROJECT_USERS",
		10: "METHOD_SIGN_OUT",
	}
	Method_value = map[string]int32{
		"METHOD_UNSPECIFIED":             0,
		"METHOD_PING":                    1,
		"METHOD_GET_VERSION":             2,
		"METHOD_GET_INSTALL_IDENTITY":    3,
		"METHOD_COMPLETE_ONBOARDING":     4,
		"METHOD_REMOVE_INSTALL_IDENTITY": 5,
		"METHOD_GET_ACTIVE_PROJECT":      6,
		"METHOD_OPEN_PROJECT":            7,
		"METHOD_REMOVE_ACTIVE_PROJECT":   8,
		"METHOD_LIST_PROJECT_USERS":      9,
		"METHOD_SIGN_OUT":                10,
	}
)

func (x Method) Enum() *Method {
	p := new(Method)
	*p = x
	return p
}

func (x Method) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Method) Descriptor() protoreflect.EnumDescriptor {
	return file_engine_proto_enumTypes[0].Descriptor()
}

func (Method) Type() protoreflect.EnumType {
	return &file_engine_proto_enumTypes[0]
}

func (x Method) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Method.Descriptor instead.
func (Method) EnumDescriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{2}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{3}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetInstallIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityDir   string                 `protobuf:"bytes,1,opt,name=identity_dir,json=identityDir,proto3" json:"identity_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstallIdentityRequest) Reset() {
	*x = GetInstallIdentityRequest{}
	mi := &file_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstallIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstallIdentityRequest) ProtoMessage() {}

func (x *GetInstallIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstallIdentityRequest.ProtoReflect.Descriptor instead.
func (*GetInstallIdentityRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{4}
}

func (x *GetInstallIdentityRequest) GetIdentityDir() string {
	if x != nil {
		return x.IdentityDir
	}
	return ""
}

type GetInstallIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstallIdentityResponse) Reset() {
	*x = GetInstallIdentityResponse{}
	mi := &file_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstallIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstallIdentityResponse) ProtoMessage() {}

func (x *GetInstallIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstallIdentityResponse.ProtoReflect.Descriptor instead.
func (*GetInstallIdentityResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{5}
}

func (x *GetInstallIdentityResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetInstallIdentityResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetInstallIdentityResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type CompleteOnboardingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityDir   string                 `protobuf:"bytes,1,opt,name=identity_dir,json=identityDir,proto3" json:"identity_dir,omitempty"`
	ParentDir     string                 `protobuf:"bytes,2,opt,name=parent_dir,json=parentDir,proto3" json:"parent_dir,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	FamilyName    string                 `protobuf:"bytes,4,opt,name=family_name,json=familyName,proto3" json:"family_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOnboardingRequest) Reset() {
	*x = CompleteOnboardingRequest{}
	mi := &file_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOnboardingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOnboardingRequest) ProtoMessage() {}

func (x *CompleteOnboardingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOnboardingRequest.ProtoReflect.Descriptor instead.
func (*CompleteOnboardingRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{6}
}

func (x *CompleteOnboardingRequest) GetIdentityDir() string {
	if x != nil {
		return x.IdentityDir
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetParentDir() string {
	if x != nil {
		return x.ParentDir
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CompleteOnboardingRequest) GetFamilyName() string {
	if x != nil {
		return x.FamilyName
	}
	return ""
}

type CompleteOnboardingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir    string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteOnboardingResponse) Reset() {
	*x = CompleteOnboardingResponse{}
	mi := &file_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteOnboardingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteOnboardingResponse) ProtoMessage() {}

func (x *CompleteOnboardingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteOnboardingResponse.ProtoReflect.Descriptor instead.
func (*CompleteOnboardingResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteOnboardingResponse) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *CompleteOnboardingResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CompleteOnboardingResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type RemoveInstallIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityDir   string                 `protobuf:"bytes,1,opt,name=identity_dir,json=identityDir,proto3" json:"identity_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveInstallIdentityRequest) Reset() {
	*x = RemoveInstallIdentityRequest{}
	mi := &file_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveInstallIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveInstallIdentityRequest) ProtoMessage() {}

func (x *RemoveInstallIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveInstallIdentityRequest.ProtoReflect.Descriptor instead.
func (*RemoveInstallIdentityRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveInstallIdentityRequest) GetIdentityDir() string {
	if x != nil {
		return x.IdentityDir
	}
	return ""
}

type RemoveInstallIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveInstallIdentityResponse) Reset() {
	*x = RemoveInstallIdentityResponse{}
	mi := &file_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveInstallIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveInstallIdentityResponse) ProtoMessage() {}

func (x *RemoveInstallIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveInstallIdentityResponse.ProtoReflect.Descriptor instead.
func (*RemoveInstallIdentityResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{9}
}

type GetActiveProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityDir   string                 `protobuf:"bytes,1,opt,name=identity_dir,json=identityDir,proto3" json:"identity_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveProjectRequest) Reset() {
	*x = GetActiveProjectRequest{}
	mi := &file_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveProjectRequest) ProtoMessage() {}

func (x *GetActiveProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveProjectRequest.ProtoReflect.Descriptor instead.
func (*GetActiveProjectRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{10}
}

func (x *GetActiveProjectRequest) GetIdentityDir() string {
	if x != nil {
		return x.IdentityDir
	}
	return ""
}

type GetActiveProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	ProjectDir    string                 `protobuf:"bytes,2,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveProjectResponse) Reset() {
	*x = GetActiveProjectResponse{}
	mi := &file_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveProjectResponse) ProtoMessage() {}

func (x *GetActiveProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveProjectResponse.ProtoReflect.Descriptor instead.
func (*GetActiveProjectResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{11}
}

func (x *GetActiveProjectResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetActiveProjectResponse) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

type OpenProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityDir   string                 `protobuf:"bytes,1,opt,name=identity_dir,json=identityDir,proto3" json:"identity_dir,omitempty"`
	ProjectDir    string                 `protobuf:"bytes,2,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	AdoptUserId   string                 `protobuf:"bytes,4,opt,name=adopt_user_id,json=adoptUserId,proto3" json:"adopt_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenProjectRequest) Reset() {
	*x = OpenProjectRequest{}
	mi := &file_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenProjectRequest) ProtoMessage() {}

func (x *OpenProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenProjectRequest.ProtoReflect.Descriptor instead.
func (*OpenProjectRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{12}
}

func (x *OpenProjectRequest) GetIdentityDir() string {
	if x != nil {
		return x.IdentityDir
	}
	return ""
}

func (x *OpenProjectRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *OpenProjectRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *OpenProjectRequest) GetAdoptUserId() string {
	if x != nil {
		return x.AdoptUserId
	}
	return ""
}

type OpenProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir    string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenProjectResponse) Reset() {
	*x = OpenProjectResponse{}
	mi := &file_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenProjectResponse) ProtoMessage() {}

func (x *OpenProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenProjectResponse.ProtoReflect.Descriptor instead.
func (*OpenProjectResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{13}
}

func (x *OpenProjectResponse) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

func (x *OpenProjectResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *OpenProjectResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type RemoveActiveProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityDir   string                 `protobuf:"bytes,1,opt,name=identity_dir,json=identityDir,proto3" json:"identity_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveActiveProjectRequest) Reset() {
	*x = RemoveActiveProjectRequest{}
	mi := &file_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveActiveProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveActiveProjectRequest) ProtoMessage() {}

func (x *RemoveActiveProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveActiveProjectRequest.ProtoReflect.Descriptor instead.
func (*RemoveActiveProjectRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveActiveProjectRequest) GetIdentityDir() string {
	if x != nil {
		return x.IdentityDir
	}
	return ""
}

type RemoveActiveProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveActiveProjectResponse) Reset() {
	*x = RemoveActiveProjectResponse{}
	mi := &file_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveActiveProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveActiveProjectResponse) ProtoMessage() {}

func (x *RemoveActiveProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveActiveProjectResponse.ProtoReflect.Descriptor instead.
func (*RemoveActiveProjectResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{15}
}

type ListProjectUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectDir    string                 `protobuf:"bytes,1,opt,name=project_dir,json=projectDir,proto3" json:"project_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectUsersRequest) Reset() {
	*x = ListProjectUsersRequest{}
	mi := &file_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectUsersRequest) ProtoMessage() {}

func (x *ListProjectUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectUsersRequest.ProtoReflect.Descriptor instead.
func (*ListProjectUsersRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{16}
}

func (x *ListProjectUsersRequest) GetProjectDir() string {
	if x != nil {
		return x.ProjectDir
	}
	return ""
}

type ProjectUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DisplayName   string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectUser) Reset() {
	*x = ProjectUser{}
	mi := &file_engine_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectUser) ProtoMessage() {}

func (x *ProjectUser) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectUser.ProtoReflect.Descriptor instead.
func (*ProjectUser) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{17}
}

func (x *ProjectUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ProjectUser) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

type ListProjectUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*ProjectUser         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProjectUsersResponse) Reset() {
	*x = ListProjectUsersResponse{}
	mi := &file_engine_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProjectUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProjectUsersResponse) ProtoMessage() {}

func (x *ListProjectUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProjectUsersResponse.ProtoReflect.Descriptor instead.
func (*ListProjectUsersResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{18}
}

func (x *ListProjectUsersResponse) GetUsers() []*ProjectUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type SignOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityDir   string                 `protobuf:"bytes,1,opt,name=identity_dir,json=identityDir,proto3" json:"identity_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignOutRequest) Reset() {
	*x = SignOutRequest{}
	mi := &file_engine_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutRequest) ProtoMessage() {}

func (x *SignOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutRequest.ProtoReflect.Descriptor instead.
func (*SignOutRequest) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{19}
}

func (x *SignOutRequest) GetIdentityDir() string {
	if x != nil {
		return x.IdentityDir
	}
	return ""
}

type SignOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignOutResponse) Reset() {
	*x = SignOutResponse{}
	mi := &file_engine_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutResponse) ProtoMessage() {}

func (x *SignOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engine_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutResponse.ProtoReflect.Descriptor instead.
func (*SignOutResponse) Descriptor() ([]byte, []int) {
	return file_engine_proto_rawDescGZIP(), []int{20}
}

var File_engine_proto protoreflect.FileDescriptor

const file_engine_proto_rawDesc = "" +
	"\n" +
	"\fengine.proto\x12\x15provenencia.engine.v1\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x13\n" +
	"\x11GetVersionRequest\".\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\">\n" +
	"\x19GetInstallIdentityRequest\x12!\n" +
	"\fidentity_dir\x18\x01 \x01(\tR\videntityDir\"n\n" +
	"\x1aGetInstallIdentityResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"\xa1\x01\n" +
	"\x19CompleteOnboardingRequest\x12!\n" +
	"\fidentity_dir\x18\x01 \x01(\tR\videntityDir\x12\x1d\n" +
	"\n" +
	"parent_dir\x18\x02 \x01(\tR\tparentDir\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1f\n" +
	"\vfamily_name\x18\x04 \x01(\tR\n" +
	"familyName\"y\n" +
	"\x1aCompleteOnboardingResponse\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"A\n" +
	"\x1cRemoveInstallIdentityRequest\x12!\n" +
	"\fidentity_dir\x18\x01 \x01(\tR\videntityDir\"\x1f\n" +
	"\x1dRemoveInstallIdentityResponse\"<\n" +
	"\x17GetActiveProjectRequest\x12!\n" +
	"\fidentity_dir\x18\x01 \x01(\tR\videntityDir\"Q\n" +
	"\x18GetActiveProjectResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12\x1f\n" +
	"\vproject_dir\x18\x02 \x01(\tR\n" +
	"projectDir\"\x9f\x01\n" +
	"\x12OpenProjectRequest\x12!\n" +
	"\fidentity_dir\x18\x01 \x01(\tR\videntityDir\x12\x1f\n" +
	"\vproject_dir\x18\x02 \x01(\tR\n" +
	"projectDir\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\"\n" +
	"\radopt_user_id\x18\x04 \x01(\tR\vadoptUserId\"r\n" +
	"\x13OpenProjectResponse\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\"?\n" +
	"\x1aRemoveActiveProjectRequest\x12!\n" +
	"\fidentity_dir\x18\x01 \x01(\tR\videntityDir\"\x1d\n" +
	"\x1bRemoveActiveProjectResponse\":\n" +
	"\x17ListProjectUsersRequest\x12\x1f\n" +
	"\vproject_dir\x18\x01 \x01(\tR\n" +
	"projectDir\"I\n" +
	"\vProjectUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\"T\n" +
	"\x18ListProjectUsersResponse\x128\n" +
	"\x05users\x18\x01 \x03(\v2\".provenencia.engine.v1.ProjectUserR\x05users\"3\n" +
	"\x0eSignOutRequest\x12!\n" +
	"\fidentity_dir\x18\x01 \x01(\tR\videntityDir\"\x11\n" +
	"\x0fSignOutResponse*\xbc\x02\n" +
	"\x06Method\x12\x16\n" +
	"\x12METHOD_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vMETHOD_PING\x10\x01\x12\x16\n" +
	"\x12METHOD_GET_VERSION\x10\x02\x12\x1f\n" +
	"\x1bMETHOD_GET_INSTALL_IDENTITY\x10\x03\x12\x1e\n" +
	"\x1aMETHOD_COMPLETE_ONBOARDING\x10\x04\x12\"\n" +
	"\x1eMETHOD_REMOVE_INSTALL_IDENTITY\x10\x05\x12\x1d\n" +
	"\x19METHOD_GET_ACTIVE_PROJECT\x10\x06\x12\x17\n" +
	"\x13METHOD_OPEN_PROJECT\x10\a\x12 \n" +
	"\x1cMETHOD_REMOVE_ACTIVE_PROJECT\x10\b\x12\x1d\n" +
	"\x19METHOD_LIST_PROJECT_USERS\x10\t\x12\x13\n" +
	"\x0fMETHOD_SIGN_OUT\x10\n" +
	"B1Z/github.com/mendahu/provenencia/api/proto/engineb\x06proto3"

var (
	file_engine_proto_rawDescOnce sync.Once
	file_engine_proto_rawDescData []byte
)

func file_engine_proto_rawDescGZIP() []byte {
	file_engine_proto_rawDescOnce.Do(func() {
		file_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)))
	})
	return file_engine_proto_rawDescData
}

var file_engine_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_engine_proto_goTypes = []any{
	(Method)(0),                           // 0: provenencia.engine.v1.Method
	(*PingRequest)(nil),                   // 1: provenencia.engine.v1.PingRequest
	(*PingResponse)(nil),                  // 2: provenencia.engine.v1.PingResponse
	(*GetVersionRequest)(nil),             // 3: provenencia.engine.v1.GetVersionRequest
	(*GetVersionResponse)(nil),            // 4: provenencia.engine.v1.GetVersionResponse
	(*GetInstallIdentityRequest)(nil),     // 5: provenencia.engine.v1.GetInstallIdentityRequest
	(*GetInstallIdentityResponse)(nil),    // 6: provenencia.engine.v1.GetInstallIdentityResponse
	(*CompleteOnboardingRequest)(nil),     // 7: provenencia.engine.v1.CompleteOnboardingRequest
	(*CompleteOnboardingResponse)(nil),    // 8: provenencia.engine.v1.CompleteOnboardingResponse
	(*RemoveInstallIdentityRequest)(nil),  // 9: provenencia.engine.v1.RemoveInstallIdentityRequest
	(*RemoveInstallIdentityResponse)(nil), // 10: provenencia.engine.v1.RemoveInstallIdentityResponse
	(*GetActiveProjectRequest)(nil),       // 11: provenencia.engine.v1.GetActiveProjectRequest
	(*GetActiveProjectResponse)(nil),      // 12: provenencia.engine.v1.GetActiveProjectResponse
	(*OpenProjectRequest)(nil),            // 13: provenencia.engine.v1.OpenProjectRequest
	(*OpenProjectResponse)(nil),           // 14: provenencia.engine.v1.OpenProjectResponse
	(*RemoveActiveProjectRequest)(nil),    // 15: provenencia.engine.v1.RemoveActiveProjectRequest
	(*RemoveActiveProjectResponse)(nil),   // 16: provenencia.engine.v1.RemoveActiveProjectResponse
	(*ListProjectUsersRequest)(nil),       // 17: provenencia.engine.v1.ListProjectUsersRequest
	(*ProjectUser)(nil),                   // 18: provenencia.engine.v1.ProjectUser
	(*ListProjectUsersResponse)(nil),      // 19: provenencia.engine.v1.ListProjectUsersResponse
	(*SignOutRequest)(nil),                // 20: provenencia.engine.v1.SignOutRequest
	(*SignOutResponse)(nil),               // 21: provenencia.engine.v1.SignOutResponse
}
var file_engine_proto_depIdxs = []int32{
	18, // 0: provenencia.engine.v1.ListProjectUsersResponse.users:type_name -> provenencia.engine.v1.ProjectUser
	1,  // [1:1] is the sub-list for method output_type
	1,  // [1:1] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_engine_proto_init() }
func file_engine_proto_init() {
	if File_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engine_proto_rawDesc), len(file_engine_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_engine_proto_goTypes,
		DependencyIndexes: file_engine_proto_depIdxs,
		EnumInfos:         file_engine_proto_enumTypes,
		MessageInfos:      file_engine_proto_msgTypes,
	}.Build()
	File_engine_proto = out.File
	file_engine_proto_goTypes = nil
	file_engine_proto_depIdxs = nil
}
